### ISSUE TITLE
Time left stops

### ISSUE THREAD

**Issue by cheymos** [neki-dev/izowave#2]
The timer stops some time after the game starts.
Maybe problem with CORS policy settings?

Screenshot:

<img width="1507" src="https://user-images.githubusercontent.com/36195448/226692796-25c5cf60-d53c-400d-9307-d30be3db3efb.png">

**Comment by neki-dev** [comment]
Hello! Yes, I see a problem with CORS, but this only affects sending of statistics.
In the near future I will check reason for stopping the timer.

**Comment by neki-dev** [comment]
Fixed in v0.22.0
