### ISSUE TITLE
How did you build out the isometric world/scene?

### ISSUE THREAD

**Issue by douglasg14b** [neki-dev/izowave#5]
Hey! This is a cool project, I'm just getting started with Phaser and am trying to build an isometric scene for a game of mine.

Found a link to this from https://github.com/photonstorm/phaser/issues/6215

I'm browsing through your code, but am struggling to figure out how/where you are building the iso scene out, would you be so kind as to link me to files I should read through to better understand how this works? Or if you have a long-form description of hw you went about this, I would love to read it!

Thanks ^_^

**Comment by neki-dev** [comment]
Hello! You need to iterate 2d map matrix and get positions and depth for map tiles.

Convert matrix position to tile position - https://github.com/neki-dev/izowave/blob/master/src/game/scenes/world/level/level.ts#L284
 
Convert matrix position to tile depth - https://github.com/neki-dev/izowave/blob/master/src/game/scenes/world/level/level.ts#L301

Full example:

```js
const TILE_WIDTH = 42; // Width of tile image
const TILE_HEIGHT = 48; // Height of tile image
const TILE_ORIGIN = 0.25; // Center of tile top

for (let y = 0; y < map.height; y++) {
  for (let x = 0; x < map.width; x++) {
    const z = ... // Matrix position Z from your data

    const tilePositionX = (x - y) * (TILE_WIDTH * 0.5); // Isometric tile position X
    const tilePositionY = (x + y) * (TILE_HEIGHT * TILE_ORIGIN) - (z * (TILE_HEIGHT * 0.5)); // Isometric tile position Y
    const tileDepth = y + (z * 999);  // Isometric tile depth

    const tile = this.scene.add.image(tilePositionX, tilePositionY, ...);

    tile.setOrigin(0.5, TILE_ORIGIN);
    tile.setDepth(tileDepth);
  }
}
```

**Comment by douglasg14b** [comment]
Thank you for the explanation, code example AND diagram!

You're awesome.

**Comment by neki-dev** [comment]
I fixed example:

`const tileDepth = y + (z * 999);` to `const tileDepth = tilePositionY + (z * 999);`
